name: Redeploy the Kristal Website with New Documentation

on:
    push:
        branches:
        - ldoc-test
    workflow_dispatch:


jobs:
    redeploy-wiki:
        runs-on: ubuntu-latest
        steps:
          - env: 
                KRISTAL_WEBSITE_REDEPLOY_WEBHOOK: ${{ secrets.KRISTAL_WEBSITE_REDEPLOY_WEBHOOK }}
            run: 
                curl -X POST "$KRISTAL_WEBSITE_REDEPLOY_WEBHOOK"
    

