on:
    pull_request:
      branches:
      - ldoc-test
    push:
      branches:
      - ldoc-test

jobs:
  ldoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lua LDoc
        uses: lunarmodules/ldoc@v1.5.0
